### ISSUE TITLE
Location and Preceptor on RPP app (Future Fix)

### ISSUE THREAD

**Issue by aasam028** [uoForms/RPP#6]
Add two additional fields to the TeamMembers Column showing the location and Preceptor of the various residents.

**Comment by hannhow** [comment]
Changes made to Demo server. Please have it retested.

**Comment by aasam028** [comment]
Tested. It's fine on the test server. We can replicate it on the production server.
![location](https://cloud.githubusercontent.com/assets/15662347/13094779/13ffd8ae-d4db-11e5-8dc6-ecb1d6ddef2a.PNG)

**Comment by hannhow** [comment]
Changes made to production server. Pending retest.

**Comment by aasam028** [comment]
Tested.. 
![prod loc](https://cloud.githubusercontent.com/assets/15662347/13199383/2c7a0c32-d7f2-11e5-9149-440e3b7d3d4e.PNG)
