### ISSUE TITLE
Change the "After Hours" as being Defaulted

### ISSUE THREAD

**Issue by aasam028** [uoForms/RPP#9]
The After hours in the App keeps defaulting based on what was previously selected.

<img width="1021" alt="rpp_afterhours" src="https://cloud.githubusercontent.com/assets/15662347/12463538/fdde6c7e-bf91-11e5-9617-dffceda03d70.PNG">

**Comment by hannhow** [comment]
The page contains two individual radio buttons (Yes and No). Therefore the 'remember' function of second button (No) will always override the first one (Yes), resulting in the fact that it is always set to No regardless of previous choice.

**Comment by hannhow** [comment]
For a quick fix, "After Hours" is set to "No" by default on Demo server. Please have it tested.

**Comment by aasam028** [comment]
Tested the changes on the Demo Server.. It is working as required. 
This can be replicated on the production server.

<img width="1031" alt="after hr" src="https://cloud.githubusercontent.com/assets/15662347/13198968/3a241c04-d7e5-11e5-9d69-36a35648f0f8.PNG">
<img width="825" alt="after hr 2" src="https://cloud.githubusercontent.com/assets/15662347/13198970/3c5706d0-d7e5-11e5-9dac-0d7749b45124.PNG">

**Comment by hannhow** [comment]
Changes made to production server. Pending retest.

**Comment by aasam028** [comment]
Tested

<img width="1049" alt="prod_after" src="https://cloud.githubusercontent.com/assets/15662347/13199418/d2666028-d7f2-11e5-8432-5b245563ddbc.PNG">
